### ISSUE TITLE
Check that netlifys pricing is reasonable for our scale

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/acecentre.org.uk#214]

**Comment by willwade** [comment]
Loving this issue. Are you thinking Re: functions ? Or build and deploy ?

**Comment by gavinhenderson** [comment]
Mainly thinking functions. Every page load will cause at least 2 function triggers. We currently have 125,000 function calls per month and 100 hours of run time. Not sure how much traffic it will take to hit that. 

Although to be honest the next level is only $25 pm and you get 2,000,000 calls per month and 1000 hours so that will be enough. Need to have a look into the pricing works, don't want to get caught with a bunch of over use charges

Our bandwidth will be low because we handle images with cloudinary. Our build minutes will be low because we use Github. So im not really worried about those.

**Comment by willwade** [comment]
Alternatives? I guess azure, our own VM, aws etc

**Comment by gavinhenderson** [comment]
Yeah those would work. Depends what we are after, aws or azure would be cheapest but most involved.

Netlify is super simple so an alternative would have to be offset with the maintanence cost.

**Comment by gavinhenderson** [comment]
My plan is to hopefully stay with Netlify because I really love it. But this is mostly about doing my due dilligence to make sure we don't get caught out with a daft bill when we launch

**Comment by gavinhenderson** [comment]
I've had a dig about. I removed the cart count in the navbar. It was using too many requests and wasn't worth it. People can just click it to know how many things are in the cart.

I have a dashboard tracking the number of function calls. Ill keep an eye on it but we should be well under it
